apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Stores clones of repositories to perform Git operations.
  labels:
    deploy: sourcegraph
  name: gitserver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitserver
  serviceName: gitserver
  template:
    metadata:
      labels:
        app: gitserver
        group: backend
        type: gitserver
    spec:
      containers:
      - args:
        - run
        env:
        image: index.docker.io/sourcegraph/gitserver:3.16.0@sha256:31987e80f7137fe635add74f24d60872db8702d4fb07b5e00dcd4877ab9bcb21
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: rpc
          timeoutSeconds: 5
        name: gitserver
        ports:
        - containerPort: 3178
          name: rpc
        resources:
          limits:
            cpu: "4"
            memory: 8G
          requests:
            cpu: "4" 
            memory: 8G
        volumeMounts:
        - mountPath: /data/repos
          name: repos
        # See the customization guide (../../../docs/configure.md) for information
        # about configuring gitserver to use an SSH key
        # - mountPath: /root/.ssh
        #   name: ssh
      securityContext:
        runAsUser: 0
      volumes:
      - name: repos
      # See the customization guide (../../../docs/configure.md) for information
      # about configuring gitserver to use an SSH key
      # - name: ssh
      #   secret:
      #     defaultMode: 384
      #     secretName: gitserver-ssh
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # The size of disk used to mirror your git repositories.
          # If you change this, also change indexed-search's disk size.
          storage: 200Gi
      storageClassName: sourcegraph
