apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
  name: indexed-search
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  serviceName: indexed-search
  template:
    metadata:
      labels:
        app: indexed-search
    spec:
      containers:
      - env:
        image: index.docker.io/sourcegraph/zoekt-webserver:0.0.20200429072931-1a9304f@sha256:600015b185019a77f5bb4503eda5f219e0ac856ad38c345bbaba3032865181ce
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-webserver
        ports:
        - containerPort: 6070
          name: http
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: data
      - env:
        image: index.docker.io/sourcegraph/zoekt-indexserver:0.0.20200429072931-1a9304f@sha256:8594efce8a5acb962430e8ac93f2ee5f2c75172f24c1004b25e6fd08dc0f57e0
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-indexserver
        ports:
        - containerPort: 6072
          name: index-http
        resources:
          # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
          # lower lag between a new commit and it being indexed for search.
          limits:
            cpu: "8"
            memory: 8G
          requests:
            cpu: "4"
            memory: 4G
        volumeMounts:
        - mountPath: /data
          name: data
      securityContext:
        runAsUser: 0
      volumes:
      - name: data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        deploy: sourcegraph
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # The size of disk to used for search indexes.
          # This should typically be gitserver disk size multipled by the number of gitserver shards.
          storage: 200Gi
      storageClassName: sourcegraph
